type Query {
  user(id: Int): User!
  users: [User!]!
  post(id: Int): Post!
  posts: [Post!]!
}

type User {
  id: Int!
  name: String!
  posts: [Post!]!
}

type Post {
  id: Int!
  message: String!
  user: User!
}
